// Catalogo delle immagini che il computer di bordo può mostrare (scelte da reference/)
export const IMMAGINI = [
  // 651-007 Lunz am Meer, la barca di riferimento
  { id: "lunz-am-meer-regata-aerea", file: "/img/bordo/lunz-am-meer-regata-aerea.jpg", titolo: "Lunz am Meer", didascalia: "In regata", descrizione: "Lunz am Meer vista dall'alto mentre risale il vento sbandata, equipaggio in rosso e bianco schierato in falchetta, scafo bianco con fascia rossa e coperta in teak.", fonte: "reference/photos/lunz-am-meer.png" },
  { id: "lunz-am-meer-swan-cup", file: "/img/bordo/lunz-am-meer-swan-cup.jpg", titolo: "Lunz am Meer", didascalia: "Rolex Swan Cup", descrizione: "Lunz am Meer in regata alla Rolex Swan Cup di Porto Cervo, con il nome ben leggibile sulla murata e l'equipaggio in rosso al lavoro in pozzetto.", fonte: "reference/photos_web/exterior/unknown_swanclassic_sailing_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "lunz-am-meer-spinnaker-aut-2895", file: "/img/bordo/lunz-am-meer-spinnaker-aut-2895.jpg", titolo: "Lunz am Meer", didascalia: "AUT 2895", descrizione: "Lunz am Meer con spinnaker rosso e randa che porta il numero velico AUT 2895, davanti alle rocce di granito della Sardegna settentrionale.", fonte: "reference/photos/lunz-am-meer-social-11.jpg" },
  { id: "lunz-am-meer-in-cantiere", file: "/img/bordo/lunz-am-meer-in-cantiere.jpg", titolo: "Lunz am Meer", didascalia: "A secco in cantiere", descrizione: "Lunz am Meer fuori dall'acqua su invasatura, con l'opera viva rossa e la pinna di chiglia con bulbo della versione Mod ben visibili, una Vespa parcheggiata sotto lo scafo.", fonte: "reference/photos/lunz-am-meer-social-16.jpg" },
  { id: "lunz-am-meer-equipaggio-premiazione", file: "/img/bordo/lunz-am-meer-equipaggio-premiazione.jpg", titolo: "L'equipaggio", didascalia: "Festa sul podio", descrizione: "L'equipaggio giovane di Lunz am Meer, in maglie bianche e pantaloni rossi, festeggia sul palco di una premiazione con i trofei in mano; evento e anno non indicati.", fonte: "reference/photos/lunz-am-meer-social-35.jpg" },
  { id: "lunz-am-meer-acquerello", file: "/img/bordo/lunz-am-meer-acquerello.jpg", titolo: "Lunz am Meer", didascalia: "Ritratto ad acquerello", descrizione: "Acquerello di Lunz am Meer di bolina con lo spinnaker rosso e l'equipaggio in falchetta, accompagnato da un breve testo a mano in inglese sulla storia della barca.", fonte: "reference/photos/lunz-am-meer-social-13.webp" },

  // 651-001 Futuro (ex Yellowdrama V)
  { id: "futuro-dettagli-gialli", file: "/img/bordo/futuro-dettagli-gialli.jpg", titolo: "Futuro", didascalia: "I dettagli gialli", descrizione: "Lo scafo 651-001 di bolina con mare formato, con i dettagli gialli dei primi anni sullo scafo e sulla capottina, prima del passaggio al blu.", fonte: "reference/photos/futuro-1.png" },
  { id: "futuro-regata", file: "/img/bordo/futuro-regata.jpg", titolo: "Futuro", didascalia: "Di bolina", descrizione: "Futuro molto sbandata di bolina, con il nome Futuro e il porto Hamburg scritti sullo specchio di poppa e l'equipaggio al lavoro in pozzetto.", fonte: "reference/photos/futuro-sailat-2.png" },
  { id: "futuro-dopo-la-tempesta", file: "/img/bordo/futuro-dopo-la-tempesta.jpg", titolo: "Futuro", didascalia: "Lorient, gennaio 2023", descrizione: "Futuro rovesciata a terra nel piazzale di Lorient dopo la tempesta Gérard del 16 gennaio 2023, con l'albero spezzato: l'incidente che la escluse dall'Ocean Globe Race.", fonte: "reference/photos/futuro-social-3.jpg" },
  { id: "targa-scafo-651-001", file: "/img/bordo/targa-scafo-651-001.jpg", titolo: "Targa del cantiere", didascalia: "651/001, giugno 1982", descrizione: "La targa in ottone Nautor's Swan a bordo del primo scafo, con la firma di German Frers e la scritta 651/001 June 82.", fonte: "reference/photos_web/interior/hull-001_other_1.jpg, da https://www.xboat.es/4271-NAUTOR-SWAN_SWAN-651.html" },
  { id: "cabina-armatore-651-001", file: "/img/bordo/cabina-armatore-651-001.jpg", titolo: "Cabina armatore", didascalia: "Scafo 651-001", descrizione: "La cabina armatore a poppa dello scafo 651-001, con letto centrale, due divanetti laterali e boiserie in teak.", fonte: "reference/photos_web/interior/hull-001_owner_cabin_1.jpg, da https://www.xboat.es/4271-NAUTOR-SWAN_SWAN-651.html" },

  // 651-002 Adrienne II
  { id: "adrienne-ii-in-navigazione", file: "/img/bordo/adrienne-ii-in-navigazione.jpg", titolo: "Adrienne II", didascalia: "Allungata a 70 piedi", descrizione: "Adrienne II in navigazione a vele spiegate con bandiera svedese, nella versione allungata a 70 piedi con il tendalino sul pozzetto.", fonte: "reference/photos/adrienne-ii.jpeg" },
  { id: "adrienne-ii-dinette", file: "/img/bordo/adrienne-ii-dinette.jpg", titolo: "La dinette", didascalia: "Adrienne II", descrizione: "La dinette di Adrienne II: divani a U blu, tavolo in legno lucido, libreria, scaletta del tambuccio e osteriggi sul cielo, tutto in teak.", fonte: "reference/photos/adrienne-navark-3.jpg" },
  { id: "adrienne-ii-verricelli", file: "/img/bordo/adrienne-ii-verricelli.jpg", titolo: "I verricelli", didascalia: "Pozzetto di Adrienne II", descrizione: "Un grosso winch Harken in pozzetto su Adrienne II con la scotta avvolta, e sotto i pulsanti rossi dei comandi elettrici dei verricelli.", fonte: "reference/photos_web/deck/adrienne-ii_cockpit_3.jpg, da https://navark.se/en/bat/swan-70-3/" },
  { id: "tavola-profilo-pianta-651-002", file: "/img/bordo/tavola-profilo-pianta-651-002.jpg", titolo: "La tavola di progetto", didascalia: "Profilo e pianta", descrizione: "La tavola ufficiale Nautor's Swan dello scafo 651-002 con il profilo di carena, chiglia e timone e la pianta degli interni: il riferimento da cui è nato il modello 3D del museo.", fonte: "reference/swan651-002-profile-layout.jpeg" },

  // 651-004 Ichiban
  { id: "ichiban-di-bolina", file: "/img/bordo/ichiban-di-bolina.jpg", titolo: "Ichiban", didascalia: "Arcipelago di Stoccolma", descrizione: "Ichiban, Swan 651 Extended, di bolina fra gli scogli, con il carattere giapponese del nome sulla vela di prua e l'opera viva rossa.", fonte: "reference/photos_web/exterior/ichiban_sailing_1.jpg, da https://ichibansailingevent.se/content/files/pdf/sy_ichiban_the_classic_swan_651_extended.pdf" },
  { id: "ichiban-salone-ovale", file: "/img/bordo/ichiban-salone-ovale.jpg", titolo: "Il salone ovale", didascalia: "Ichiban", descrizione: "Il salone ovale di Ichiban, nato dal rifacimento degli interni del 1991: tavolo apparecchiato per la cena, divano a ferro di cavallo, libreria e applique.", fonte: "reference/photos_web/interior/ichiban_saloon_1.jpg, da https://viewyacht.com/ichiban" },

  // 651-005 Show Me
  { id: "show-me-in-navigazione", file: "/img/bordo/show-me-in-navigazione.jpg", titolo: "Show Me", didascalia: "Vele bianche, mare blu", descrizione: "Show Me in navigazione veloce con randa e genoa, equipaggio in coperta, in una foto d'epoca dai colori un po' sbiaditi.", fonte: "reference/photos/show-me.png" },
  { id: "show-me-barografo", file: "/img/bordo/show-me-barografo.jpg", titolo: "Il barografo", didascalia: "Show Me", descrizione: "Il barografo in ottone di Show Me nella sua teca di teak accanto al carteggio, con il quadro elettrico originale e la dinette sullo sfondo: legno e ottone degli interni Swan.", fonte: "reference/photos_web/interior/show-me_nav_1.jpg, da https://www.seattleyachts.com/used-yachts-for-sale/65-nautor-swan-651-1983-show-me/2831939_1" },
  { id: "show-me-pozzetto", file: "/img/bordo/show-me-pozzetto.jpg", titolo: "Il pozzetto", didascalia: "Show Me", descrizione: "Il pozzetto di Show Me visto dall'alto in porto: ruota del timone, colonnina strumenti e i grandi winch cromati ai lati.", fonte: "reference/photos/show-me-5.webp" },

  // 651-006 Rosbeg (ex Gaetana)
  { id: "rosbeg-regata", file: "/img/bordo/rosbeg-regata.jpg", titolo: "Rosbeg", didascalia: "Swan Cup, Porto Cervo", descrizione: "Lo scafo 651-006, scafo blu scuro con il numero 12 a prua, ripreso dall'alto mentre corre sbandato alla Rolex Swan Cup con l'equipaggio in falchetta; nome di quel momento non certo, Gaetana o Rosbeg.", fonte: "reference/photos/rosbeg-social-3.jpg" },

  // 651-008 Deneb
  { id: "deneb-armada", file: "/img/bordo/deneb-armada.jpg", titolo: "Deneb", didascalia: "Nave scuola spagnola", descrizione: "Deneb, scafo blu scuro, in navigazione a vela in acque chiare con a bordo un gruppo numeroso, verosimilmente allievi della Marina spagnola.", fonte: "reference/photos/deneb.png" },

  // 651-009 Whisper of V
  { id: "whisper-of-v-monaco", file: "/img/bordo/whisper-of-v-monaco.jpg", titolo: "Whisper of V", didascalia: "Porto di Monaco", descrizione: "Uno Swan 651 indicato come Whisper of V, ormeggiato nel porto di Monaco con bandiera rossa britannica a poppa e ospiti in pozzetto.", fonte: "reference/photos/whisper.png" },

  // 651-010 Tihama
  { id: "tihama-alla-fonda", file: "/img/bordo/tihama-alla-fonda.jpg", titolo: "Tihama", didascalia: "Alla fonda", descrizione: "Tihama, scafo blu scuro, ferma davanti a una costa rocciosa bassa, vista di fianco con le vele ammainate.", fonte: "reference/photos/tihama.png" },

  // 651-011 Spirit of Helsinki (ex Fazer Finland, Second Wind)
  { id: "fazer-finland-whitbread", file: "/img/bordo/fazer-finland-whitbread.jpg", titolo: "Fazer Finland", didascalia: "Whitbread 1985-86", descrizione: "Fazer Finland, oggi Spirit of Helsinki, al lasco con randa e genoa, il nome dello sponsor sulla murata: la barca che arrivò terza alla Whitbread 1985-86.", fonte: "reference/photos/spirit-of-helsinki-fazer-1.jpg" },
  { id: "fazer-finland-spinnaker-l71", file: "/img/bordo/fazer-finland-spinnaker-l71.jpg", titolo: "Fazer Finland", didascalia: "Spinnaker L 71", descrizione: "Fazer Finland con il grande spinnaker blu con la scritta FAZER e il numero velico L 71, l'epoca della Whitbread di metà anni Ottanta.", fonte: "reference/photos/spirit-of-helsinki-fazer-3.jpg" },
  { id: "second-wind-california", file: "/img/bordo/second-wind-california.jpg", titolo: "Second Wind", didascalia: "Gli anni californiani", descrizione: "La stessa barca col nome Second Wind, ormeggiata in California con il nome sullo specchio di poppa: il periodo della vittoria di divisione alla Transpac 2015.", fonte: "reference/photos_web/exterior/second_wind_stern_quarter_1.jpg, da https://www.fraseryachts.com/en/yacht/second-wind/" },
  { id: "spirit-of-helsinki-ocean-globe", file: "/img/bordo/spirit-of-helsinki-ocean-globe.jpg", titolo: "Spirit of Helsinki", didascalia: "Ocean Globe Race", descrizione: "Spirit of Helsinki di bolina con il numero 71 sulla murata, bandiera finlandese e i colori dell'Ocean Globe Race 2023-24.", fonte: "reference/photos/spirit-of-helsinki.jpg" },
  { id: "spirit-of-helsinki-citta-del-capo", file: "/img/bordo/spirit-of-helsinki-citta-del-capo.jpg", titolo: "Spirit of Helsinki", didascalia: "Città del Capo, 2023", descrizione: "Spirit of Helsinki vista da poppa all'arrivo a Città del Capo, con la Table Mountain sullo sfondo, dopo la vittoria della prima tappa dell'Ocean Globe Race 2023.", fonte: "reference/photos_web/exterior/spirit_of_helsinki_stern_1.jpg, da https://www.spiritofhelsinki.fi/" },

  // 651-014 White Knight of NY
  { id: "white-knight-of-ny", file: "/img/bordo/white-knight-of-ny.jpg", titolo: "White Knight of NY", didascalia: "Scafo blu notte", descrizione: "White Knight of NY, scafo blu notte con il nome sulla murata, a motore lungo una costa rocciosa con la randa raccolta nel lazy bag.", fonte: "reference/photos/white-knight-of-ny.png" },

  // 651-016 Geronimo
  { id: "geronimo-di-bolina", file: "/img/bordo/geronimo-di-bolina.jpg", titolo: "Geronimo", didascalia: "Porto: Amsterdam", descrizione: "Geronimo, scafo blu con il nome e la scritta Amsterdam sullo specchio di poppa, di bolina con l'equipaggio seduto in falchetta.", fonte: "reference/photos/geronimo-baroncini-5.JPG" },

  // 651-017 Aurora
  { id: "aurora-ormeggiata", file: "/img/bordo/aurora-ormeggiata.jpg", titolo: "Aurora", didascalia: "Costruita nel 1989", descrizione: "Aurora, costruita nel 1989, vista di tre quarti da poppa all'ormeggio, con il nome sullo specchio di poppa e la capottina sul pozzetto.", fonte: "reference/photos_web/exterior/aurora_stern_quarter_1.jpg, da https://www.yachtworld.com/yacht/1989-nautor-swan-651-7874297/" },
  { id: "aurora-carteggio", file: "/img/bordo/aurora-carteggio.jpg", titolo: "Il carteggio", didascalia: "Aurora", descrizione: "La stazione di carteggio di Aurora: quadro elettrico originale con interruttori e strumenti analogici, accanto a schermi moderni, barometro e orologio in ottone.", fonte: "reference/photos_web/interior/aurora_nav_2.jpg, da https://www.yeomanyachts.com/boat-for-sale/swan-651-aurora" },

  // Scafi senza numero identificato
  { id: "sway-af-tammsvik", file: "/img/bordo/sway-af-tammsvik.jpg", titolo: "Sway af Tammsvik", didascalia: "Bandiera svedese", descrizione: "Sway af Tammsvik, Swan 651 allungato a 70 piedi, al traverso con randa e genoa e la bandiera svedese a poppa.", fonte: "reference/photos/sway.png" },
  { id: "papirusa-in-porto", file: "/img/bordo/papirusa-in-porto.jpg", titolo: "Papirusa", didascalia: "Scafo blu, Spagna", descrizione: "Papirusa, scafo blu con il nome in bianco a prua, ormeggiata di poppa a un pontile sotto un cielo limpido.", fonte: "reference/photos/papirusa-social-1.png" },
  { id: "bercut-in-porto", file: "/img/bordo/bercut-in-porto.jpg", titolo: "Bercut", didascalia: "L'unica foto", descrizione: "Bercut, lo Swan 651 meno documentato, ormeggiato in un porto con colline brulle alle spalle: è l'unica foto che ne abbiamo.", fonte: "reference/photos/bercut.jpg" },
  { id: "emocean-singapore", file: "/img/bordo/emocean-singapore.jpg", titolo: "Emocean", didascalia: "Singapore, 2018", descrizione: "Emocean, scafo blu scuro, ormeggiata alla marina ONE°15 di Singapore nel 2018, con il nome e la scritta Valletta sullo specchio di poppa.", fonte: "reference/photos/emocean.jpg" },
  { id: "indigo-vi-swan-cup", file: "/img/bordo/indigo-vi-swan-cup.jpg", titolo: "Indigo VI", didascalia: "Porto Cervo, 2016", descrizione: "Indigo VI, scafo scuro, di bolina davanti alla costa della Sardegna con l'equipaggio in bianco in falchetta, probabilmente alla Rolex Swan Cup 2016.", fonte: "reference/photos/indigo.png" },
  { id: "kingfisher-di-bolina", file: "/img/bordo/kingfisher-di-bolina.jpg", titolo: "Kingfisher", didascalia: "Swan 651 Extended", descrizione: "Kingfisher, scafo scuro, di bolina con randa e genoa davanti a una costa verde e montuosa; foto piccola, da mostrare in formato ridotto.", fonte: "reference/photos/kingfisher.png" },

  // Tavole di progetto della classe
  { id: "piano-velico-swan-651", file: "/img/bordo/piano-velico-swan-651.jpg", titolo: "Il piano velico", didascalia: "Disegno di Frers", descrizione: "Il piano velico ufficiale dello Swan 651: profilo della barca con albero, randa e fiocco, disegno al tratto su fondo bianco.", fonte: "reference/photos_web/drawings/swan651_sail_plan_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "pianta-interni-swan-651", file: "/img/bordo/pianta-interni-swan-651.jpg", titolo: "Gli interni", didascalia: "Da poppa a prua", descrizione: "La pianta degli interni dello Swan 651 vista dall'alto, prua a destra: cabina armatore a poppa, cucina e carteggio, salone al centro, cabine ospiti e bagni verso prua, gavone di prua.", fonte: "reference/photos_web/drawings/swan651_interior_layout_2.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "pianta-coperta-swan-651", file: "/img/bordo/pianta-coperta-swan-651.jpg", titolo: "La coperta", didascalia: "Vista dall'alto", descrizione: "Il disegno della coperta dello Swan 651 visto dall'alto: pozzetto a poppa, posizione dei winch, osteriggi e tuga, utile per spiegare le manovre.", fonte: "reference/photos_web/drawings/swan651_deck_layout_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
];
