// Catalogo delle immagini che il computer di bordo può mostrare (scelte da reference/).
// Il museo racconta il 651 come modello, non i singoli scafi: le foto sono presentate come
// "uno Swan 651". Fanno eccezione, come nella landing, la Whitbread di Fazer Finland (oggi
// Spirit of Helsinki) e la tavola di Adrienne II da cui nasce il modello. "fonte" resta per
// sapere da dove viene ogni file.
export const IMMAGINI = [
  // In regata
  { id: "in-regata-dall-alto", file: "/img/bordo/in-regata-dall-alto.jpg", titolo: "In regata", didascalia: "Vista dall'alto", descrizione: "Uno Swan 651 visto dall'alto mentre risale il vento sbandato, equipaggio in rosso e bianco schierato in falchetta, scafo bianco con fascia rossa e coperta in teak.", fonte: "reference/photos/lunz-am-meer.png" },
  { id: "swan-cup-porto-cervo", file: "/img/bordo/swan-cup-porto-cervo.jpg", titolo: "Rolex Swan Cup", didascalia: "Porto Cervo", descrizione: "Uno Swan 651 bianco in regata alla Rolex Swan Cup di Porto Cervo, con l'equipaggio in rosso al lavoro in pozzetto.", fonte: "reference/photos_web/exterior/unknown_swanclassic_sailing_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "spinnaker-rosso", file: "/img/bordo/spinnaker-rosso.jpg", titolo: "Lo spinnaker", didascalia: "Sardegna settentrionale", descrizione: "Uno Swan 651 con lo spinnaker rosso a riva, davanti alle rocce di granito della Sardegna settentrionale.", fonte: "reference/photos/lunz-am-meer-social-11.jpg" },
  { id: "scafo-blu-in-regata", file: "/img/bordo/scafo-blu-in-regata.jpg", titolo: "Scafo blu", didascalia: "Rolex Swan Cup", descrizione: "Uno Swan 651 blu scuro ripreso dall'alto mentre corre sbandato alla Rolex Swan Cup, con l'equipaggio in falchetta.", fonte: "reference/photos/rosbeg-social-3.jpg" },
  { id: "di-bolina-sbandata", file: "/img/bordo/di-bolina-sbandata.jpg", titolo: "Di bolina", didascalia: "Molto sbandata", descrizione: "Uno Swan 651 molto sbandato di bolina, con l'equipaggio al lavoro in pozzetto.", fonte: "reference/photos/futuro-sailat-2.png" },
  { id: "dettagli-gialli", file: "/img/bordo/dettagli-gialli.jpg", titolo: "Mare formato", didascalia: "Di bolina", descrizione: "Uno Swan 651 di bolina con mare formato, con dettagli gialli sullo scafo e sulla capottina.", fonte: "reference/photos/futuro-1.png" },
  { id: "equipaggio-in-falchetta", file: "/img/bordo/equipaggio-in-falchetta.jpg", titolo: "Di bolina", didascalia: "Equipaggio in falchetta", descrizione: "Uno Swan 651 blu di bolina con l'equipaggio seduto in falchetta.", fonte: "reference/photos/geronimo-baroncini-5.JPG" },
  { id: "di-bolina-in-sardegna", file: "/img/bordo/di-bolina-in-sardegna.jpg", titolo: "Di bolina", didascalia: "Costa sarda", descrizione: "Uno Swan 651 dallo scafo scuro di bolina davanti alla costa della Sardegna, con l'equipaggio in bianco in falchetta.", fonte: "reference/photos/indigo.png" },
  { id: "equipaggio-sul-podio", file: "/img/bordo/equipaggio-sul-podio.jpg", titolo: "L'equipaggio", didascalia: "Festa sul podio", descrizione: "L'equipaggio di uno Swan 651, in maglie bianche e pantaloni rossi, festeggia sul palco di una premiazione con i trofei in mano; evento e anno non indicati.", fonte: "reference/photos/lunz-am-meer-social-35.jpg" },
  { id: "ritratto-ad-acquerello", file: "/img/bordo/ritratto-ad-acquerello.jpg", titolo: "Un acquerello", didascalia: "Di bolina con lo spinnaker", descrizione: "Acquerello di uno Swan 651 di bolina con lo spinnaker rosso e l'equipaggio in falchetta, con un breve testo scritto a mano in inglese.", fonte: "reference/photos/lunz-am-meer-social-13.webp" },

  // In navigazione e in porto
  { id: "foto-d-epoca", file: "/img/bordo/foto-d-epoca.jpg", titolo: "Foto d'epoca", didascalia: "Randa e genoa", descrizione: "Uno Swan 651 in navigazione veloce con randa e genoa, equipaggio in coperta, in una foto d'epoca dai colori un po' sbiaditi.", fonte: "reference/photos/show-me.png" },
  { id: "versione-allungata", file: "/img/bordo/versione-allungata.jpg", titolo: "Versione allungata", didascalia: "70 piedi", descrizione: "Uno Swan 651 allungato a 70 piedi, in navigazione a vele spiegate con bandiera svedese e il tendalino sul pozzetto.", fonte: "reference/photos/adrienne-ii.jpeg" },
  { id: "allungata-al-traverso", file: "/img/bordo/allungata-al-traverso.jpg", titolo: "Al traverso", didascalia: "Versione allungata", descrizione: "Uno Swan 651 allungato a 70 piedi, al traverso con randa e genoa e la bandiera svedese a poppa.", fonte: "reference/photos/sway.png" },
  { id: "extended-fra-gli-scogli", file: "/img/bordo/extended-fra-gli-scogli.jpg", titolo: "Versione Extended", didascalia: "Fra gli scogli", descrizione: "Uno Swan 651 Extended di bolina fra gli scogli di un arcipelago nordico, con un carattere giapponese sulla vela di prua e l'opera viva rossa.", fonte: "reference/photos_web/exterior/ichiban_sailing_1.jpg, da https://ichibansailingevent.se/content/files/pdf/sy_ichiban_the_classic_swan_651_extended.pdf" },
  { id: "costa-montuosa", file: "/img/bordo/costa-montuosa.jpg", titolo: "Di bolina", didascalia: "Costa montuosa", descrizione: "Uno Swan 651 dallo scafo scuro di bolina con randa e genoa davanti a una costa verde e montuosa; foto piccola, da mostrare in formato ridotto.", fonte: "reference/photos/kingfisher.png" },
  { id: "equipaggio-numeroso", file: "/img/bordo/equipaggio-numeroso.jpg", titolo: "Tanti a bordo", didascalia: "Acque chiare", descrizione: "Uno Swan 651 blu scuro in navigazione a vela in acque chiare, con a bordo un gruppo numeroso di persone.", fonte: "reference/photos/deneb.png" },
  { id: "blu-notte", file: "/img/bordo/blu-notte.jpg", titolo: "Scafo blu notte", didascalia: "A motore", descrizione: "Uno Swan 651 blu notte a motore lungo una costa rocciosa, con la randa raccolta nel lazy bag.", fonte: "reference/photos/white-knight-of-ny.png" },
  { id: "alla-fonda", file: "/img/bordo/alla-fonda.jpg", titolo: "Alla fonda", didascalia: "Vele ammainate", descrizione: "Uno Swan 651 blu scuro fermo davanti a una costa rocciosa bassa, visto di fianco con le vele ammainate.", fonte: "reference/photos/tihama.png" },
  { id: "ormeggiata-a-monaco", file: "/img/bordo/ormeggiata-a-monaco.jpg", titolo: "In porto", didascalia: "Monaco", descrizione: "Uno Swan 651 ormeggiato nel porto di Monaco con bandiera rossa britannica a poppa e ospiti in pozzetto.", fonte: "reference/photos/whisper.png" },
  { id: "all-ormeggio", file: "/img/bordo/all-ormeggio.jpg", titolo: "All'ormeggio", didascalia: "Tre quarti da poppa", descrizione: "Uno Swan 651 visto di tre quarti da poppa all'ormeggio, con la capottina sul pozzetto.", fonte: "reference/photos_web/exterior/aurora_stern_quarter_1.jpg, da https://www.yachtworld.com/yacht/1989-nautor-swan-651-7874297/" },
  { id: "ormeggiata-in-california", file: "/img/bordo/ormeggiata-in-california.jpg", titolo: "In California", didascalia: "Ormeggiata", descrizione: "Uno Swan 651 ormeggiato in California, visto di tre quarti da poppa.", fonte: "reference/photos_web/exterior/second_wind_stern_quarter_1.jpg, da https://www.fraseryachts.com/en/yacht/second-wind/" },
  { id: "al-pontile", file: "/img/bordo/al-pontile.jpg", titolo: "Al pontile", didascalia: "Scafo blu", descrizione: "Uno Swan 651 blu ormeggiato di poppa a un pontile sotto un cielo limpido.", fonte: "reference/photos/papirusa-social-1.png" },
  { id: "porto-fra-le-colline", file: "/img/bordo/porto-fra-le-colline.jpg", titolo: "In porto", didascalia: "Colline brulle", descrizione: "Uno Swan 651 ormeggiato in un porto con colline brulle alle spalle.", fonte: "reference/photos/bercut.jpg" },
  { id: "marina-di-singapore", file: "/img/bordo/marina-di-singapore.jpg", titolo: "Ai tropici", didascalia: "Singapore", descrizione: "Uno Swan 651 blu scuro ormeggiato in una marina di Singapore, visto da poppa.", fonte: "reference/photos/emocean.jpg" },

  // A terra
  { id: "a-secco-in-cantiere", file: "/img/bordo/a-secco-in-cantiere.jpg", titolo: "A secco", didascalia: "In cantiere", descrizione: "Uno Swan 651 fuori dall'acqua su invasatura, con l'opera viva rossa e la pinna di chiglia con bulbo della versione Mod ben visibili, una Vespa parcheggiata sotto lo scafo.", fonte: "reference/photos/lunz-am-meer-social-16.jpg" },
  { id: "dopo-la-tempesta", file: "/img/bordo/dopo-la-tempesta.jpg", titolo: "Dopo la tempesta", didascalia: "A terra", descrizione: "Uno Swan 651 rovesciato a terra nel piazzale di un cantiere dopo una tempesta, con l'albero spezzato.", fonte: "reference/photos/futuro-social-3.jpg" },

  // Interni e coperta
  { id: "targa-del-cantiere", file: "/img/bordo/targa-del-cantiere.jpg", titolo: "Targa del cantiere", didascalia: "Firmata Frers", descrizione: "La targa in ottone Nautor's Swan a bordo di uno Swan 651, con la firma di German Frers, il numero di scafo e la data di costruzione.", fonte: "reference/photos_web/interior/hull-001_other_1.jpg, da https://www.xboat.es/4271-NAUTOR-SWAN_SWAN-651.html" },
  { id: "cabina-armatore", file: "/img/bordo/cabina-armatore.jpg", titolo: "Cabina armatore", didascalia: "A poppa", descrizione: "La cabina armatore a poppa di uno Swan 651, con letto centrale, due divanetti laterali e boiserie in teak.", fonte: "reference/photos_web/interior/hull-001_owner_cabin_1.jpg, da https://www.xboat.es/4271-NAUTOR-SWAN_SWAN-651.html" },
  { id: "dinette", file: "/img/bordo/dinette.jpg", titolo: "La dinette", didascalia: "Teak e divani blu", descrizione: "La dinette di uno Swan 651: divani a U blu, tavolo in legno lucido, libreria, scaletta del tambuccio e osteriggi sul cielo, tutto in teak.", fonte: "reference/photos/adrienne-navark-3.jpg" },
  { id: "salone-ovale", file: "/img/bordo/salone-ovale.jpg", titolo: "Il salone ovale", didascalia: "Interni rifatti", descrizione: "Il salone ovale di uno Swan 651 con gli interni rifatti: tavolo apparecchiato per la cena, divano a ferro di cavallo, libreria e applique. Non è la disposizione originale.", fonte: "reference/photos_web/interior/ichiban_saloon_1.jpg, da https://viewyacht.com/ichiban" },
  { id: "barografo", file: "/img/bordo/barografo.jpg", titolo: "Il barografo", didascalia: "Legno e ottone", descrizione: "Il barografo in ottone di uno Swan 651 nella sua teca di teak accanto al carteggio, con il quadro elettrico originale e la dinette sullo sfondo: legno e ottone degli interni Swan.", fonte: "reference/photos_web/interior/show-me_nav_1.jpg, da https://www.seattleyachts.com/used-yachts-for-sale/65-nautor-swan-651-1983-show-me/2831939_1" },
  { id: "carteggio", file: "/img/bordo/carteggio.jpg", titolo: "Il carteggio", didascalia: "Vecchio e nuovo", descrizione: "La stazione di carteggio di uno Swan 651: quadro elettrico originale con interruttori e strumenti analogici, accanto a schermi moderni, barometro e orologio in ottone.", fonte: "reference/photos_web/interior/aurora_nav_2.jpg, da https://www.yeomanyachts.com/boat-for-sale/swan-651-aurora" },
  { id: "pozzetto-dall-alto", file: "/img/bordo/pozzetto-dall-alto.jpg", titolo: "Il pozzetto", didascalia: "Visto dall'alto", descrizione: "Il pozzetto di uno Swan 651 visto dall'alto in porto: ruota del timone, colonnina strumenti e i grandi winch cromati ai lati.", fonte: "reference/photos/show-me-5.webp" },
  { id: "verricelli-elettrici", file: "/img/bordo/verricelli-elettrici.jpg", titolo: "I verricelli", didascalia: "In pozzetto", descrizione: "Un grosso winch Harken nel pozzetto di uno Swan 651 con la scotta avvolta, e sotto i pulsanti rossi dei comandi elettrici dei verricelli.", fonte: "reference/photos_web/deck/adrienne-ii_cockpit_3.jpg, da https://navark.se/en/bat/swan-70-3/" },

  // La Whitbread 1985-86: Fazer Finland, oggi Spirit of Helsinki (citata anche nella landing)
  { id: "fazer-finland-whitbread", file: "/img/bordo/fazer-finland-whitbread.jpg", titolo: "Fazer Finland", didascalia: "Whitbread 1985-86", descrizione: "Fazer Finland, oggi Spirit of Helsinki, al lasco con randa e genoa e il nome dello sponsor sulla murata: lo Swan 651 che arrivò terzo alla Whitbread 1985-86.", fonte: "reference/photos/spirit-of-helsinki-fazer-1.jpg" },
  { id: "fazer-finland-spinnaker-l71", file: "/img/bordo/fazer-finland-spinnaker-l71.jpg", titolo: "Fazer Finland", didascalia: "Spinnaker L 71", descrizione: "Fazer Finland con il grande spinnaker blu con la scritta FAZER e il numero velico L 71, l'epoca della Whitbread di metà anni Ottanta.", fonte: "reference/photos/spirit-of-helsinki-fazer-3.jpg" },
  { id: "spirit-of-helsinki-di-bolina", file: "/img/bordo/spirit-of-helsinki-di-bolina.jpg", titolo: "Spirit of Helsinki", didascalia: "Oggi", descrizione: "Spirit of Helsinki, la ex Fazer Finland, di bolina con il numero 71 sulla murata e la bandiera finlandese.", fonte: "reference/photos/spirit-of-helsinki.jpg" },
  { id: "spirit-of-helsinki-citta-del-capo", file: "/img/bordo/spirit-of-helsinki-citta-del-capo.jpg", titolo: "Spirit of Helsinki", didascalia: "Città del Capo", descrizione: "Spirit of Helsinki, la ex Fazer Finland, vista da poppa a Città del Capo, con la Table Mountain sullo sfondo.", fonte: "reference/photos_web/exterior/spirit_of_helsinki_stern_1.jpg, da https://www.spiritofhelsinki.fi/" },

  // Tavole di progetto
  { id: "tavola-profilo-pianta-651-002", file: "/img/bordo/tavola-profilo-pianta-651-002.jpg", titolo: "La tavola di progetto", didascalia: "Profilo e pianta", descrizione: "La tavola ufficiale Nautor's Swan di Adrienne II, scafo 651-002, con il profilo di carena, chiglia e timone e la pianta degli interni: il riferimento da cui è nato il modello 3D del museo.", fonte: "reference/swan651-002-profile-layout.jpeg" },
  { id: "piano-velico-swan-651", file: "/img/bordo/piano-velico-swan-651.jpg", titolo: "Il piano velico", didascalia: "Disegno di Frers", descrizione: "Il piano velico ufficiale dello Swan 651: profilo della barca con albero, randa e fiocco, disegno al tratto su fondo bianco.", fonte: "reference/photos_web/drawings/swan651_sail_plan_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "pianta-interni-swan-651", file: "/img/bordo/pianta-interni-swan-651.jpg", titolo: "Gli interni", didascalia: "Da poppa a prua", descrizione: "La pianta degli interni dello Swan 651 vista dall'alto, prua a destra: cabina armatore a poppa, cucina e carteggio, salone al centro, cabine ospiti e bagni verso prua, gavone di prua.", fonte: "reference/photos_web/drawings/swan651_interior_layout_2.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
  { id: "pianta-coperta-swan-651", file: "/img/bordo/pianta-coperta-swan-651.jpg", titolo: "La coperta", didascalia: "Vista dall'alto", descrizione: "Il disegno della coperta dello Swan 651 visto dall'alto: pozzetto a poppa, posizione dei winch, osteriggi e tuga, utile per spiegare le manovre.", fonte: "reference/photos_web/drawings/swan651_deck_layout_1.jpg, da https://swanclassicbyfrers.org/our-boats/swan-651-1982-1991/" },
];
